{
 "title": "Tango Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "devices",
    "query": "label_values(device_attribute, device)"
   },
   {
    "name": "device",
    "query": "label_values(device_attribute, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Exporter info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of attributes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "attribute_count " }
     ]
    },
    {
     "title": "Total number of read attributes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "attribute_read_count " }
     ]
    },
    {
     "title": "Total number of spectrum attributes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "spectrum_attribute_count " }
     ]
    },
    {
     "title": "Total number of image attributes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "image_attribute_count " }
     ]
    },
    {
     "title": "Error count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "error_count " }
     ]
    },
    {
     "title": "Not managed attributes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "not_managed_attribute_count" }
     ]
    },
    { "title": "TANGO Database information", "type": "ryantxu-ajax-panel", "gridPos": { "h": 13, "w": 18, "x": 0, "y": 5 } }
   ]
  },
  {
   "title": "DatabaseDS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attribute list for device sys/database/2",
     "type": "inaf-ska-tango-device-view",
     "description": "Attribute list for device sys/database/2",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\", name=~\"State|Status|StoredProcedureRelease\"}  "
      }
     ]
    },
    {
     "title": "Timing minimum on Databaseds",
     "type": "graph",
     "gridPos": { "h": 12, "w": 10, "x": 9, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\",name=\"Timing_minimum\"}",
       "legendFormat": "{{x}}"
      }
     ]
    },
    {
     "title": "Timing average on Databaseds",
     "type": "graph",
     "gridPos": { "h": 13, "w": 9, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\",name=\"Timing_average\"}",
       "legendFormat": "{{x}}"
      }
     ]
    },
    {
     "title": "Timing maximum on Databaseds",
     "type": "graph",
     "gridPos": { "h": 11, "w": 10, "x": 9, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\",name=\"Timing_maximum\"}",
       "legendFormat": "{{x}}"
      }
     ]
    },
    {
     "title": "Timing calls on Databaseds",
     "type": "graph",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\",name=\"Timing_calls\"}",
       "legendFormat": "{{x}}"
      }
     ]
    }
   ]
  },
  { "title": "Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Float scalar values on $device",
   "type": "graph",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "device_attribute{device=\"$device\",dim_x=\"1\",dim_y=\"0\", type=\"float\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Attribute list for device $device",
   "type": "inaf-ska-tango-device-view",
   "description": "Attribute list for device $device",
   "gridPos": { "h": 14, "w": 7, "x": 13, "y": 3 },
   "targets": [
    {
     "expr": "device_attribute{device=~\"$device\"}  "
    }
   ]
  },
  { "title": "$device  - List commands", "type": "ryantxu-ajax-panel", "gridPos": { "h": 12, "w": 13, "x": 0, "y": 15 } },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Float scalar values on $devices",
   "type": "graph",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "device_attribute{device=~\"$devices\",dim_x=\"1\",dim_y=\"0\", type=\"float\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Attribute list for device $devices",
   "type": "inaf-ska-tango-device-view",
   "description": "Attribute list for device $devices",
   "gridPos": { "h": 16, "w": 10, "x": 13, "y": 28 },
   "targets": [
    {
     "expr": "device_attribute{device=~\"$devices\"}  "
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  { "title": "Start up telescope command", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 45 } }
 ]
}