# Default values for tango-grafana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 5

minikube: true

storageClass: standard

minikube: true

tango_exporter:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-exporter
    tag: 1.0.0
    pullPolicy: IfNotPresent

grafana_with_tango_plugin:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: grafana-tango-plugins
    tag: 1.0.0
    pullPolicy: IfNotPresent

tango_gql_proxy:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tangogql-proxy
    tag: 1.0.0
    pullPolicy: IfNotPresent
