global:
    evaluation_interval: 15s
    scrape_interval: 15s
    scrape_timeout: 10s
  
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - 192.168.93.61:9090
  
- job_name: tango
  static_configs:
  - targets:
    - 192.168.93.61:32767
  