{
 "title": "Archiver",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Attribute configuration",
   "type": "table",
   "gridPos": { "h": 16, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT att_name, data_type FROM att_conf INNER JOIN att_conf_data_type\r\nON att_conf.att_conf_data_type_id = att_conf_data_type.att_conf_data_type_id LIMIT 1000;"
    }
   ]
  },
  {
   "title": "Scalar Double (windspeed)",
   "type": "graph",
   "gridPos": { "h": 16, "w": 18, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  data_time AS \"time\",\n  att_name,\n  value_r\nFROM att_scalar_devdouble_rw INNER JOIN att_conf ON att_conf.att_conf_id = att_scalar_devdouble_rw.att_conf_id\nWHERE\n  $__timeFilter(data_time)\nORDER BY data_time"
    }
   ]
  },
  {
   "title": "Scalar Long (TangoTest)",
   "type": "graph",
   "gridPos": { "h": 16, "w": 18, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  data_time AS \"time\",\n  att_name,\n  value_r\nFROM att_scalar_devulong_rw INNER JOIN att_conf ON att_conf.att_conf_id = att_scalar_devulong_rw.att_conf_id\nWHERE\n  $__timeFilter(data_time)\nORDER BY data_time"
    }
   ]
  },
  {
   "title": "Array Dev Double",
   "type": "table",
   "gridPos": { "h": 16, "w": 18, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  data_time as time_sec,\r\n  att_conf.name,\r\n  idx,\r\n  value_r as value\r\nFROM att_array_devdouble_rw INNER JOIN att_conf ON att_conf.att_conf_id = att_array_devdouble_rw.att_conf_id\r\nWHERE att_conf.att_name = 'tango://databaseds-tango-base-test.integration.svc.cluster.local:10000/mid_d0001/elt/master/desiredpointing'\r\nAND data_time = (select max(data_time) from att_array_devdouble_rw)"
    }
   ]
  }
 ]
}