{
 "title": "TangoDB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Device Table",
   "type": "table",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT *\nFROM device" }
   ]
  },
  {
   "title": "Device Properties",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 15 },
   "targets": [
    { "rawSql": "SELECT *\nFROM property_device" }
   ]
  },
  {
   "title": "Event Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 23 },
   "targets": [
    { "rawSql": "SELECT *\nFROM event" }
   ]
  }
 ]
}