{
 "title": "State analysis",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "State Analysis View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device States",
   "type": "inaf-ska-tango-device-view",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "device_attribute{name=\"State\", device=~\"mid_csp/elt/subarray_01|mid_csp_cbf/fspsubarray/01_01|mid_csp_cbf/sub_elt/subarray_01|mid_csp_cbf/vcc/002|mid_csp_cbf/vcc/004|mid_sdp/elt/subarray_1|ska_mid/tm_subarray_node/1\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Device with obsState not IDLE",
   "type": "inaf-ska-tango-device-view",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "device_attribute{name=\"obsState\", str_value!=\"IDLE\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  { "title": "Start-up telescope", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 } },
  { "title": "Stand by telescope", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 } },
  { "title": "Assign Resources", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 9, "y": 10 } },
  { "title": "Release Resources", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 13, "y": 10 } },
  { "title": "Configure1", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 } },
  { "title": "Scan1", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 } },
  { "title": "EndSB", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 9, "y": 14 } },
  { "title": "Configure2", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 } },
  { "title": "Scan2", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 } },
  {
   "title": "Devices view",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true
  },
  {
   "title": "ska_mid/tm_subarray_node/1",
   "type": "inaf-ska-tango-device-view",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "device_attribute{device=\"ska_mid/tm_subarray_node/1\",name=~\"State|obsState|receptorIDList|activityMessage\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "mid_sdp/elt/subarray_1",
   "type": "inaf-ska-tango-device-view",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 23 },
   "targets": [
    {
     "expr": "device_attribute{device=\"mid_sdp/elt/subarray_1\",name=~\"State|obsState\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "mid_d0002/elt/master",
   "type": "inaf-ska-tango-device-view",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 28 },
   "targets": [
    {
     "expr": "device_attribute{device=\"mid_d0002/elt/master\",name=~\"State|pointingState\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "mid_d0001/elt/master",
   "type": "inaf-ska-tango-device-view",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "device_attribute{device=\"mid_d0001/elt/master\",name=~\"State|pointingState\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "mid_csp/elt/subarray_01",
   "type": "inaf-ska-tango-device-view",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 33 },
   "targets": [
    {
     "expr": "device_attribute{device=\"mid_csp/elt/subarray_01\",name=~\"State|obsState\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}