NAME:=tangogql-proxy

VERSION:=1.0.0

TAG:=1.0.0

include ../make/Makefile.mk

# docker_start: 
# 	@docker run -d -p=5000:5000 --env AUTH_URL=http://192.168.93.69:32763/login --env TANGOGQL_URL=http://192.168.93.69:32762/db --name tangogql-proxy tangogql-proxy:1.0.0

# docker_start:
# 	@docker stop tangogql-proxy || true; \
# 	docker rm tangogql-proxy || true

# all: build