apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: tango-grafana
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 32765

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasource
  namespace: tango-grafana
data: 
    datasource.yaml: |
      apiVersion: 1
      deleteDatasources:
        - name: 'Prometheus'
          orgId: 1
      datasources:
      - name: 'Prometheus'
        type: 'prometheus'
        access: 'proxy'
        orgId: 1
        url: http://prometheus-service:9090
        basicAuth: false
        isDefault: true
        editable: false

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana-deployment
  namespace: tango-grafana
  labels:
    app: grafana
spec:
  serviceName: grafana-service
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:7.0.3
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: data
          mountPath: /var/lib/grafana
        - name: config
          mountPath: /etc/grafana/provisioning/datasources
        - name: plugins
          mountPath: /var/lib/grafana/plugins
      volumes:
      - name: config
        configMap:
          name: grafana-provisioning-datasource
      - name: data
        hostPath:
          path: /home/ubuntu/tango-grafana-data/grafana_data/
      - name: plugins
        hostPath:
          path: /home/ubuntu/TANGO-grafana/grafana/grafana-plugins/
