apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: prometheus-service
  type: NodePort
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 32766

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Release.Namespace }}
data: 
    prometheus.yml: |
      global:
        evaluation_interval: 5s
        scrape_interval: 5s
        scrape_timeout: 5s

      scrape_configs:
      - job_name: tango
        static_configs:
        - targets:
        {{ $count := .Values.replicas | int }}
        {{ range until $count }}
          - tango-exporter-service-{{ . }}
        {{ end }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus-service
spec:
  serviceName: prometheus-service
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-service
  template:
    metadata:
      labels:
        app: prometheus-service
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        args: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--storage.tsdb.retention.time=2d"]
        volumeMounts:
        - name: data
          mountPath: /prometheus
        - name: config
          mountPath: /etc/prometheus
      volumes:
      - name: config
        configMap:
          name: prometheus-config
      - name: data
        persistentVolumeClaim:
          claimName: prom-tango-grafana

