apiVersion: v1
kind: Service
metadata:
  name: tango-gql-proxy-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: tango-gql-proxy-service
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32764

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tango-gql-proxy-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: tango-gql-proxy-service
spec:
  serviceName: tango-gql-proxy-service
  replicas: 1
  selector:
    matchLabels:
      app: tango-gql-proxy-service
  template:
    metadata:
      labels:
        app: tango-gql-proxy-service
    spec:
      containers:
      - name: tangogql-proxy
        image: "{{ .Values.tango_gql_proxy.image.registry }}/{{ .Values.tango_gql_proxy.image.image }}:{{ .Values.tango_gql_proxy.image.tag }}"
        imagePullPolicy: {{ .Values.tango_gql_proxy.image.pullPolicy }}
        ports:
        - containerPort: 5000
        env:
        - name: AUTH_URL
          value: http://webjive-webjive-test.integration.svc.cluster.local:8080/login
        - name: TANGOGQL_URL
          value: http://webjive-webjive-test.integration.svc.cluster.local:5004/db

