apiVersion: v1
kind: Service
metadata:
  name: tango-gql-proxy-service
  namespace: tango-grafana
spec:
  selector:
    app: tango-gql-proxy
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32764

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tango-gql-proxy-deployment
  namespace: tango-grafana
  labels:
    app: tango-gql-proxy
spec:
  serviceName: tango-gql-proxy-service
  replicas: 1
  selector:
    matchLabels:
      app: tango-gql-proxy
  template:
    metadata:
      labels:
        app: tango-gql-proxy
    spec:
      containers:
      - name: tangogql-proxy
        image: tangogql-proxy:1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: AUTH_URL
          value: http://webjive-webjive-test.integration.svc.cluster.local:8080/login
        - name: TANGOGQL_URL
          value: http://webjive-webjive-test.integration.svc.cluster.local:5004/db

