{{ $count := .Values.replicas | int }}

{{ range until $count }}
---
apiVersion: v1
kind: Service
metadata:
  name: tango-exporter-service-{{ . }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: tango-exporter-service-{{ . }}
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tango-exporter-deployment-{{ . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: tango-exporter-service-{{ . }}
spec:
  serviceName: tango-exporter-service-{{ . }}
  replicas: 1
  selector:
    matchLabels:
      app: tango-exporter-service-{{ . }}
  template:
    metadata:
      labels:
        app: tango-exporter-service-{{ . }}
    spec:
      containers:
      - name: tango-exporter
        image: "{{ $.Values.tango_exporter.image.registry }}/{{ $.Values.tango_exporter.image.image }}:{{ $.Values.tango_exporter.image.tag }}"
        imagePullPolicy: {{ $.Values.tango_exporter.image.pullPolicy }}
        ports:
        - containerPort: 8000
        env:
        - name: TANGO_HOST
          value: databaseds-tango-base-test.integration.svc.cluster.local:10000
        command: ["python"]
        args: ["/code/collector.py", "-i {{ . }}", "-r {{ $count }}"]
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          exec:
            command:
            - sh
            - -c
            - "curl http://localhost:8000/metrics --connect-timeout 5"

{{end}}