{
 "title": "Archiver",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Archiver attribute configurations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attribute configuration",
     "type": "table",
     "gridPos": { "h": 20, "w": 15, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT att_name, data_type FROM att_conf INNER JOIN att_conf_data_type\r\nON att_conf.att_conf_data_type_id = att_conf_data_type.att_conf_data_type_id LIMIT 1000;"
      }
     ]
    }
   ]
  },
  {
   "title": "Attributes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scalar Double (windspeed)",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  data_time AS \"time\",\n  att_name,\n  value_r\nFROM att_scalar_devdouble_rw INNER JOIN att_conf ON att_conf.att_conf_id = att_scalar_devdouble_rw.att_conf_id\nWHERE\n  $__timeFilter(data_time)\nORDER BY data_time"
      }
     ]
    },
    {
     "title": "Scalar Long (TangoTest)",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  data_time AS \"time\",\n  att_name,\n  value_r\nFROM att_scalar_devulong_rw INNER JOIN att_conf ON att_conf.att_conf_id = att_scalar_devulong_rw.att_conf_id\nWHERE\n  $__timeFilter(data_time)\nORDER BY data_time"
      }
     ]
    },
    {
     "title": "Scalar Double (windspeed) Plotly",
     "type": "natel-plotly-panel",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT\n  data_time AS \"time\",\n  att_name,\n  value_r\nFROM att_scalar_devdouble_rw INNER JOIN att_conf ON att_conf.att_conf_id = att_scalar_devdouble_rw.att_conf_id\nWHERE\n  $__timeFilter(data_time) AND att_name = 'tango://databaseds-tango-base-test.integration.svc.cluster.local:10000/mid_d0004/elt/master/windspeed'\nORDER BY data_time"
      }
     ]
    }
   ]
  },
  { "title": "Plotly", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Desired Pointing (time interval)",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  data_time as time_sec,\r\n  att_conf.name,\r\n  idx,\r\n  value_r as value\r\nFROM att_array_devdouble_rw INNER JOIN att_conf ON att_conf.att_conf_id = att_array_devdouble_rw.att_conf_id\r\nWHERE att_conf.att_name = 'tango://databaseds-tango-base-test.integration.svc.cluster.local:10000/mid_d0001/elt/master/desiredpointing'\r\nAND $__timeFilter(data_time)\r\nORDER BY data_time desc "
    }
   ]
  },
  {
   "title": "Desired Pointing (Latest)",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  att_conf.name,\r\n  idx,\r\n  value_r as value\r\nFROM att_array_devdouble_rw INNER JOIN att_conf ON att_conf.att_conf_id = att_array_devdouble_rw.att_conf_id\r\nWHERE att_conf.att_name = 'tango://databaseds-tango-base-test.integration.svc.cluster.local:10000/mid_d0001/elt/master/desiredpointing'\r\norder by data_time desc\r\nlimit 3"
    }
   ]
  }
 ]
}