{
 "title": "Tango Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "devices",
    "query": "label_values(device_attribute, device)"
   },
   {
    "name": "device",
    "query": "label_values(device_attribute, device)"
   }
  ]
 },
 "panels": [
  { "title": "Exporter info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Attributes count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(attribute_count)" }
   ]
  },
  {
   "title": "Read attributes count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(attribute_read_count)" }
   ]
  },
  {
   "title": "Spectrum attributes count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(spectrum_attribute_count)" }
   ]
  },
  {
   "title": "Image attributes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(image_attribute_count)" }
   ]
  },
  {
   "title": "Error count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(error_count)" }
   ]
  },
  {
   "title": "Error attribute count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(error_attr_count)" }
   ]
  },
  {
   "title": "Not managed attributes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(not_managed_attribute_count)"
    }
   ]
  },
  { "title": "TANGO Database information", "type": "ryantxu-ajax-panel", "gridPos": { "h": 13, "w": 20, "x": 0, "y": 5 } },
  {
   "title": "DatabaseDS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attribute list for device sys/database/2",
     "type": "inaf-ska-tango-device-view",
     "description": "Attribute list for device sys/database/2",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\", name=~\"State|Status|StoredProcedureRelease\"}  "
      }
     ]
    },
    {
     "title": "Timing average on Databaseds",
     "type": "graph",
     "gridPos": { "h": 13, "w": 10, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\",name=\"Timing_average\"}",
       "legendFormat": "{{x}}"
      }
     ]
    },
    {
     "title": "Timing minimum on Databaseds",
     "type": "graph",
     "gridPos": { "h": 13, "w": 10, "x": 10, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\",name=\"Timing_minimum\"}",
       "legendFormat": "{{x}}"
      }
     ]
    },
    {
     "title": "Timing calls on Databaseds",
     "type": "graph",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\",name=\"Timing_calls\"}",
       "legendFormat": "{{x}}"
      }
     ]
    },
    {
     "title": "Timing maximum on Databaseds",
     "type": "graph",
     "gridPos": { "h": 12, "w": 10, "x": 10, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "device_attribute{device=\"sys/database/2\",name=\"Timing_maximum\"}",
       "legendFormat": "{{x}}"
      }
     ]
    }
   ]
  },
  { "title": "Device View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Float scalar values on $device",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "device_attribute{device=\"$device\",dim_x=\"1\",dim_y=\"0\", type=\"float\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Attribute list for device $device",
   "type": "inaf-ska-tango-device-view",
   "description": "Attribute list for device $device",
   "gridPos": { "h": 25, "w": 11, "x": 11, "y": 20 },
   "targets": [
    {
     "expr": "device_attribute{device=~\"$device\"}  "
    }
   ]
  },
  { "title": "$device  - List commands", "type": "ryantxu-ajax-panel", "gridPos": { "h": 12, "w": 11, "x": 0, "y": 33 } },
  { "title": "Multi-Device View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Float scalar values multi-devices",
   "type": "graph",
   "gridPos": { "h": 17, "w": 11, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "device_attribute{device=~\"$devices\",dim_x=\"1\",dim_y=\"0\", type=\"float\"}",
     "legendFormat": "{{device}} {{name}}"
    }
   ]
  },
  {
   "title": "Attribute list for devices",
   "type": "inaf-ska-tango-device-view",
   "gridPos": { "h": 17, "w": 11, "x": 11, "y": 46 },
   "targets": [
    {
     "expr": "device_attribute{device=~\"$devices\"}  "
    }
   ]
  },
  { "title": "ObsState and commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "obsState (not idle)",
   "type": "inaf-ska-tango-device-view",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "device_attribute{name=\"obsState\", str_value!=\"IDLE\"}"
    }
   ]
  },
  {
   "title": "obsState",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "device_attribute{name=\"obsState\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Start up telescope command", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 20, "y": 64 } }
 ]
}