{
 "title": "State analysis",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "State, obsState and pointing state",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace(device_attribute{name=~\"State|obsState|pointingState\", device=~\"ska_mid/tm_subarray_node/1|mid_csp/elt/subarray_01|mid_sdp/elt/subarray_1|mid_d0001/elt/master|mid_d0002/elt/master\"}, \"str_value\", \"1\", \"str_value\", \".*\")",
     "legendFormat": "{{device}}/{{name}}"
    }
   ]
  },
  {
   "title": "State",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 18, "y": 0 },
   "content": "<ul>\n<li>ON = 0</li>\n<li>OFF = 1</li>\n<li>CLOSE = 2</li>\n<li>OPEN = 3</li>\n<li>INSERT = 4</li>\n<li>EXTRACT = 5</li>\n<li>MOVING = 6</li>\n<li>STANDBY = 7</li>\n<li>FAULT = 8</li>\n<li>INIT = 9</li>\n<li>RUNNING = 10</li>\n<li>ALARM = 11</li>\n<li>DISABLE = 12</li>\n<li>UNKNOWN = 13</li>\n</ul>\n\n\n\n\n\n\n"
  },
  {
   "title": "ObsState",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "content": "<ul>\n<li>IDLE = 0</li>\n<li>CONFIGURING = 1</li>\n<li>READY = 2</li>\n<li>SCANNING = 3</li>\n<li>PAUSED = 4</li>\n<li>ABORTED = 5</li>\n<li>FAULT = 6</li>\n</ul>\n\n"
  },
  {
   "title": "PointingState",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "content": "<ul>\n<li>READY = 0</li>\n<li>SLEW = 1</li>\n<li>TRACK = 2</li>\n<li>SCAN = 3</li>\n<li>RESERVED = 4</li>\n</ul>\n\n"
  },
  {
   "title": "State Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device States",
     "type": "inaf-ska-tango-device-view",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "device_attribute{name=\"State\", device=~\"mid_csp/elt/subarray_01|mid_csp_cbf/fspsubarray/01_01|mid_csp_cbf/sub_elt/subarray_01|mid_csp_cbf/vcc/002|mid_csp_cbf/vcc/004|mid_sdp/elt/subarray_1|ska_mid/tm_subarray_node/1\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Device with obsState not IDLE",
     "type": "inaf-ska-tango-device-view",
     "gridPos": { "h": 12, "w": 9, "x": 9, "y": 13 },
     "targets": [
      {
       "expr": "device_attribute{name=\"obsState\", str_value!=\"IDLE\"}",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "TM Subarray 1",
   "type": "inaf-ska-tango-device-view",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "device_attribute{device=\"ska_mid/tm_subarray_node/1\",name=~\"State|obsState|receptorIDList|activityMessage\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "TM Subarray 1 Activitiy messages",
   "type": "inaf-ska-tango-device-view",
   "gridPos": { "h": 23, "w": 9, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "device_attribute{device=\"ska_mid/tm_subarray_node/1\",name=~\"activityMessage\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Subarrays SDP/CSP",
   "type": "inaf-ska-tango-device-view",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "device_attribute{device=~\"mid_csp/elt/subarray_01||mid_sdp/elt/subarray_1\",name=~\"State|obsState|receptorIDList|activityMessage\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Dishes",
   "type": "inaf-ska-tango-device-view",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "device_attribute{device=~\"mid_d0001/elt/master|mid_d0002/elt/master\",name=~\"State|pointingState\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  { "title": "Start-up telescope", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 } },
  { "title": "Stand by telescope", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 4, "y": 38 } },
  { "title": "Assign Resources", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 9, "y": 38 } },
  { "title": "Release Resources", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 13, "y": 38 } },
  { "title": "Configure1", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 } },
  { "title": "Scan1", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 4, "y": 42 } },
  { "title": "EndSB", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 9, "y": 42 } },
  { "title": "Configure2", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 46 } },
  { "title": "Scan2", "type": "inaf-tango-command", "gridPos": { "h": 4, "w": 4, "x": 4, "y": 46 } },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Error logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 51 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "ska_severity: ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 60 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "logs"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}